### ISSUE TITLE
Stops working after some time

### ISSUE THREAD

**Issue by mawoka-myblock** [mawoka-myblock/apsystemsapi-ha#3]
The integration stops working after some hours with code 3003, probably because the access token expires.

**Comment by Schmandre** [comment]
Got the same error after ~4 hours of working

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:696
First occurred: 13:04:57 (136 occurrences)
Last logged: 13:38:27

Update for sensor.apsystems_garten_all_time_production fails
Update for sensor.apsystems_garten_power fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/apsystemsapi/sensor.py", line 134, in async_update
    inverter_statistic = await self._api.get_lifetime_graph(self._inverter.inverter_dev_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apsystems_api/__init__.py", line 187, in get_lifetime_graph
    d = await _process_response(resp)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apsystems_api/__init__.py", line 33, in _process_response
    raise UnknownError(resp.status, data["code"], data)
apsystems_api.UnknownError: UnknownError - Code: 3003, Body: {'code': 3003}
```

**Comment by mawoka-myblock** [comment]
Yep, the exact same error. I'll have to check further and see if I'll be able to fix it.

**Comment by Jamann91** [comment]
Me too. I have the same problem with the same error message.

**Comment by mawoka-myblock** [comment]
A fix should be out. Try re-downloading the repo if hacs doesn't pick up the update

**Comment by Jamann91** [comment]
Thanks man!
Great job!

After update I got this Error-Log:
```

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:573
Integration: Sensor (documentation, issues)
First occurred: 19:27:47 (1 occurrences)
Last logged: 19:27:47

apsystemsapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/apsystemsapi/sensor.py", line 82, in async_update
    inverter_realtime = await self._api.get_inverter_realtime(self._inverter.inverter_dev_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apsystems_api/__init__.py", line 148, in get_inverter_realtime
    d = await _process_response(resp)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apsystems_api/__init__.py", line 35, in _process_response
    raise DeviceOffline()
apsystems_api.DeviceOffline

```

**Comment by mawoka-myblock** [comment]
That's inevitable and the error is pretty clear. Try setting it up when the inverter is online

**Comment by mawoka-myblock** [comment]
This should now be fixed since I didn't get any errors in the past hours. Will close it for now.
